import type { InvitationConfig } from "@/types/invitation";

export const invitationConfig: InvitationConfig = {
  couple: {
    groom: {
      firstName: "Lumière",
      lastName: "Ingonda",
      fullName: "Lumière Ingonda",
    },
    bride: {
      firstName: "Faïda",
      lastName: "Koko",
      fullName: "Faïda Koko",
    },
    displayNames: "Lumière & Faïda",
    fullNames: "Lumière Ingonda & Faïda Koko",
    photo: "/images/hero/couple.png",
    ceremonyPhoto: "/images/gallery/04.png",
    countdownPhoto: "/images/gallery/03.png",
  },
  event: {
    title: "Lumière & Faïda — Mariage civil",
    description:
      "Vous êtes cordialement invité(e) à célébrer le mariage civil de Lumière Ingonda et Faïda Koko.",
    // Mariage civil — 21 août 2026
    date: "2026-08-21T11:00:00",
    venue: "Paroisse Notre Dame d'Afrique",
    address: "Av. de l'École, Lemba Nord, Lemba",
    city: "Kinshasa, RDC",
    mapsQuery: "Paroisse Notre Dame d'Afrique, Avenue de l'École, Lemba, Kinshasa",
    coordinates: {
      lat: -4.37611,
      lng: 15.34044,
    },
    arrivalNote: "Merci d'arriver vers 10h45 pour être installé(e)s à l'heure.",
    parkingNote: "Stationnement possible autour de la paroisse (Lemba Nord).",
    dressNote: "Tenue élégante — palette sauge, nude et rose poudré bienvenue.",
  },
  envelope: {
    recipientLabel: "Une invitation pour vous",
    sealColor: "#D4A5AB",
    paperColor: "#F7EFE6",
    letterMessage:
      "C'est avec une immense joie que nous vous invitons à célébrer notre union civile. Votre présence rendra ce jour encore plus beau.",
  },
  program: [
    {
      time: "10h45",
      label: "Accueil des invités",
      icon: "cheers",
    },
    {
      time: "11h00",
      label: "Cérémonie civile",
      icon: "rings",
    },
    {
      time: "11h45",
      label: "Photos de groupe",
      icon: "camera",
    },
    {
      time: "12h15",
      label: "Cocktail & partage",
      icon: "cheers",
    },
  ],
  gallery: [
    "/images/gallery/01.png",
    "/images/gallery/02.png",
    "/images/gallery/03.png",
    "/images/gallery/04.png",
    "/images/gallery/05.png",
    "/images/gallery/06.png",
    "/images/gallery/07.png",
  ],
  rsvp: {
    deadline: "2026-08-10",
    maxGuests: 2,
    contactEmail: "lumiere.faida@example.com",
    contactWhatsApp: "243900000000",
    drinkCategories: [
      {
        id: "soft",
        label: "Boissons non alcoolisées",
        items: [
          { id: "coca-cola", label: "Coca-Cola" },
          { id: "fanta-orange-citron", label: "Fanta (Orange, Citron)" },
          { id: "sprite", label: "Sprite" },
          { id: "schweppes", label: "Schweppes" },
          { id: "vital-o", label: "Vital'O (eau)" },
          { id: "eau-minerale", label: "Eau minérale" },
          { id: "top-orange", label: "Top Orange" },
          { id: "top-grenadine", label: "Top Grenadine" },
          { id: "top-cola", label: "Top Cola" },
          { id: "top-tropical", label: "Top Tropical" },
          { id: "festa-orange", label: "Festa Orange" },
          { id: "festa-cola", label: "Festa Cola" },
          { id: "festa-ananas", label: "Festa Ananas" },
          { id: "festa-grenadine", label: "Festa Grenadine" },
          { id: "festa-tangawizi", label: "Festa Tangawizi (gingembre)" },
          { id: "festa-lemon", label: "Festa Lemon" },
          { id: "zen-orange", label: "Zen Orange" },
          { id: "zen-cola", label: "Zen Cola" },
          { id: "zen-grenadine", label: "Zen Grenadine" },
          { id: "zen-lemon", label: "Zen Lemon" },
          { id: "zen-tangawisi", label: "Zen Tangawisi" },
          { id: "jus-ananas", label: "Jus d'ananas" },
          { id: "jus-mangue", label: "Jus de mangue" },
          { id: "jus-orange", label: "Jus d'orange" },
          { id: "jus-passion", label: "Jus de fruits de la passion" },
          { id: "cocktail-fruits", label: "Cocktail de fruits" },
          { id: "energetiques", label: "Boissons énergétiques (XXL, Torro, Bold…)" },
        ],
      },
      {
        id: "bieres",
        label: "Bières",
        items: [
          { id: "primus", label: "Primus" },
          { id: "skol", label: "Skol" },
          { id: "heineken", label: "Heineken" },
          { id: "beaufort", label: "Beaufort" },
          { id: "turbo-king", label: "Turbo King" },
          { id: "castel", label: "Castel" },
          { id: "bavaria", label: "Bavaria" },
          { id: "1664", label: "1664" },
          { id: "guinness", label: "Guinness" },
        ],
      },
      {
        id: "vins",
        label: "Vins",
        items: [
          { id: "vin-rouge", label: "Vin rouge" },
          { id: "vin-blanc", label: "Vin blanc" },
          { id: "vin-rose", label: "Vin rosé" },
          { id: "vin-mousseux", label: "Vin mousseux" },
        ],
      },
      {
        id: "champagnes",
        label: "Champagnes",
        items: [
          { id: "moet-chandon", label: "Moët & Chandon" },
          { id: "veuve-clicquot", label: "Veuve Clicquot" },
          { id: "dom-perignon", label: "Dom Pérignon" },
          { id: "nicolas-feuillatte", label: "Nicolas Feuillatte" },
          { id: "gh-mumm", label: "GH Mumm" },
        ],
      },
      {
        id: "spiritueux",
        label: "Spiritueux",
        items: [
          { id: "johnnie-walker", label: "Johnnie Walker" },
          { id: "jack-daniels", label: "Jack Daniel's" },
          { id: "jameson", label: "Jameson" },
          { id: "chivas-regal", label: "Chivas Regal" },
          { id: "hennessy", label: "Hennessy" },
          { id: "remy-martin", label: "Rémy Martin" },
          { id: "martell", label: "Martell" },
          { id: "ballantines", label: "Ballantine's" },
          { id: "gordons-gin", label: "Gordon's Gin" },
          { id: "smirnoff-vodka", label: "Smirnoff Vodka" },
          { id: "absolut-vodka", label: "Absolut Vodka" },
          { id: "bacardi", label: "Bacardi" },
          { id: "malibu", label: "Malibu" },
        ],
      },
    ],
  },
  audio: {
    src: "/audio/violon-douce.m4a",
    label: "Douce — violon",
    volume: 0.32,
  },
  theme: {
    name: "mariage-civil",
    primary: "#E8C5C9",
    accent: "#A3B59E",
    cream: "#FAF6F1",
    powder: "#E8C5C9",
  },
  dressCode: {
    title: "Le thème",
    subtitle:
      "Inspirez-vous de ces looks pour habiller la journée — vert sauge, beige nude et rose poudré.",
    // Remplacez les images dès que vous m’envoyez les photos du thème
    looks: [
      {
        id: "look-femme",
        label: "Inspiration elle",
        description: "Élégance douce — rose poudré & nude",
        image: "/images/theme/look-femme.jpg",
      },
      {
        id: "look-homme",
        label: "Inspiration lui",
        description: "Chic naturel — sauge & beige",
        image: "/images/theme/look-homme.jpg",
      },
      {
        id: "look-palette",
        label: "Palette du jour",
        description: "Vert sauge · Beige nude · Rose poudré",
        image: "/images/theme/palette.jpg",
      },
    ],
  },
};
